-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cache
(
    key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default" NOT NULL,
    expiration integer NOT NULL,
    CONSTRAINT cache_pkey PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS public.cache_locks
(
    key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    owner character varying(255) COLLATE pg_catalog."default" NOT NULL,
    expiration integer NOT NULL,
    CONSTRAINT cache_locks_pkey PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS public.customers
(
    "idCustomer" bigint NOT NULL DEFAULT nextval('"customers_idCustomer_seq"'::regclass),
    nama character varying(255) COLLATE pg_catalog."default",
    tipe character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'lead'::character varying,
    skala character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'individu'::character varying,
    email character varying(255) COLLATE pg_catalog."default",
    telefon character varying(255) COLLATE pg_catalog."default",
    alamat character varying(255) COLLATE pg_catalog."default",
    instagram character varying(255) COLLATE pg_catalog."default",
    facebook character varying(255) COLLATE pg_catalog."default",
    twitter character varying(255) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT customers_pkey PRIMARY KEY ("idCustomer"),
    CONSTRAINT customers_email_unique UNIQUE (email),
    CONSTRAINT customers_telefon_unique UNIQUE (telefon)
);

CREATE TABLE IF NOT EXISTS public.failed_jobs
(
    id bigint NOT NULL DEFAULT nextval('failed_jobs_id_seq'::regclass),
    uuid character varying(255) COLLATE pg_catalog."default" NOT NULL,
    connection text COLLATE pg_catalog."default" NOT NULL,
    queue text COLLATE pg_catalog."default" NOT NULL,
    payload text COLLATE pg_catalog."default" NOT NULL,
    exception text COLLATE pg_catalog."default" NOT NULL,
    failed_at timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT failed_jobs_pkey PRIMARY KEY (id),
    CONSTRAINT failed_jobs_uuid_unique UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS public.job_batches
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    total_jobs integer NOT NULL,
    pending_jobs integer NOT NULL,
    failed_jobs integer NOT NULL,
    failed_job_ids text COLLATE pg_catalog."default" NOT NULL,
    options text COLLATE pg_catalog."default",
    cancelled_at integer,
    created_at integer NOT NULL,
    finished_at integer,
    CONSTRAINT job_batches_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.jobs
(
    id bigint NOT NULL DEFAULT nextval('jobs_id_seq'::regclass),
    queue character varying(255) COLLATE pg_catalog."default" NOT NULL,
    payload text COLLATE pg_catalog."default" NOT NULL,
    attempts smallint NOT NULL,
    reserved_at integer,
    available_at integer NOT NULL,
    created_at integer NOT NULL,
    CONSTRAINT jobs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.lead_process
(
    "idLeadProcess" bigint NOT NULL DEFAULT nextval('"lead_process_idLeadProcess_seq"'::regclass),
    "idCustomer" bigint,
    status character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'dibuat'::character varying,
    "idManager" bigint,
    deskripsi text COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT lead_process_pkey PRIMARY KEY ("idLeadProcess")
);

CREATE TABLE IF NOT EXISTS public.migrations
(
    id integer NOT NULL DEFAULT nextval('migrations_id_seq'::regclass),
    migration character varying(255) COLLATE pg_catalog."default" NOT NULL,
    batch integer NOT NULL,
    CONSTRAINT migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.password_reset_tokens
(
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(0) without time zone,
    CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS public.product
(
    "idProduct" bigint NOT NULL DEFAULT nextval('"product_idProduct_seq"'::regclass),
    nama character varying(255) COLLATE pg_catalog."default" NOT NULL,
    deskripsi text COLLATE pg_catalog."default",
    harga character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "gambarProduct" character varying(255) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT product_pkey PRIMARY KEY ("idProduct")
);

CREATE TABLE IF NOT EXISTS public.sales
(
    "idSales" bigint NOT NULL DEFAULT nextval('"sales_idSales_seq"'::regclass),
    "idCustomer" bigint,
    "idProduct" bigint,
    "jumlahTransaksi" character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT '0'::character varying,
    deskripsi text COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'belumdibayar'::character varying,
    invoice_file character varying(255) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT sales_pkey PRIMARY KEY ("idSales")
);

CREATE TABLE IF NOT EXISTS public.sessions
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id bigint,
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    payload text COLLATE pg_catalog."default" NOT NULL,
    last_activity integer NOT NULL,
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role integer DEFAULT 2,
    email_verified_at timestamp(0) without time zone,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    remember_token character varying(100) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_unique UNIQUE (email)
);

ALTER TABLE IF EXISTS public.lead_process
    ADD CONSTRAINT lead_process_idcustomer_foreign FOREIGN KEY ("idCustomer")
    REFERENCES public.customers ("idCustomer") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.lead_process
    ADD CONSTRAINT lead_process_idmanager_foreign FOREIGN KEY ("idManager")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sales
    ADD CONSTRAINT sales_idcustomer_foreign FOREIGN KEY ("idCustomer")
    REFERENCES public.customers ("idCustomer") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.sales
    ADD CONSTRAINT sales_idproduct_foreign FOREIGN KEY ("idProduct")
    REFERENCES public.product ("idProduct") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

END;